In [1]:
from micrograd.engine import Value, Tensor

In [2]:
import numpy as np

In [3]:
ar = np.arange(12).reshape(3, 4)
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
ar_ = np.array([Value(item) for row in ar for item in row]).reshape(3, 4)
ar_

array([[Value(data=0, grad=0), Value(data=1, grad=0),
        Value(data=2, grad=0), Value(data=3, grad=0)],
       [Value(data=4, grad=0), Value(data=5, grad=0),
        Value(data=6, grad=0), Value(data=7, grad=0)],
       [Value(data=8, grad=0), Value(data=9, grad=0),
        Value(data=10, grad=0), Value(data=11, grad=0)]], dtype=object)

In [5]:
ar_t = Tensor(ar_)
ar_t

Tensor
[[Value(data=0, grad=0) Value(data=1, grad=0) Value(data=2, grad=0)
  Value(data=3, grad=0)]
 [Value(data=4, grad=0) Value(data=5, grad=0) Value(data=6, grad=0)
  Value(data=7, grad=0)]
 [Value(data=8, grad=0) Value(data=9, grad=0) Value(data=10, grad=0)
  Value(data=11, grad=0)]]

In [6]:
ar_t.max(0)

Tensor
[Value(data=8, grad=0) Value(data=9, grad=0) Value(data=10, grad=0)
 Value(data=11, grad=0)]

In [7]:
ar_t.argmax(1)

Tensor
[Value(data=3, grad=0) Value(data=3, grad=0) Value(data=3, grad=0)]

In [8]:
np.array([5]).shape

(1,)

In [9]:
hasattr(np.array(5), '__iter__')

True

In [10]:
for item in np.array([5]):
    print(item)

5


In [11]:
len(np.array(5).shape)

0

In [12]:
np.arange(0)

array([], dtype=int32)

In [13]:
arr = np.array(5)
arr

array(5)

In [14]:
shape = arr.shape
shape

()

In [15]:
arr.reshape(shape)

array(5)

In [16]:
np.array(arr)

array(5)

In [17]:
arr.flatten().flatten()

array([5])

In [18]:
for item in np.array([]).flatten():
    print(item)

In [19]:
Tensor(5).shape()

()

In [20]:
ar_t

Tensor
[[Value(data=0, grad=0) Value(data=1, grad=0) Value(data=2, grad=0)
  Value(data=3, grad=0)]
 [Value(data=4, grad=0) Value(data=5, grad=0) Value(data=6, grad=0)
  Value(data=7, grad=0)]
 [Value(data=8, grad=0) Value(data=9, grad=0) Value(data=10, grad=0)
  Value(data=11, grad=0)]]

In [21]:
Tensor([1, 1, 1, 1])

Tensor
[Value(data=1, grad=0) Value(data=1, grad=0) Value(data=1, grad=0)
 Value(data=1, grad=0)]

In [22]:
ar_t + Tensor([1, 1, 1, 1])

Tensor
[[Value(data=1, grad=0) Value(data=2, grad=0) Value(data=3, grad=0)
  Value(data=4, grad=0)]
 [Value(data=5, grad=0) Value(data=6, grad=0) Value(data=7, grad=0)
  Value(data=8, grad=0)]
 [Value(data=9, grad=0) Value(data=10, grad=0) Value(data=11, grad=0)
  Value(data=12, grad=0)]]

In [23]:
Tensor(Tensor(ar_t))

Tensor
[[Value(data=0, grad=0) Value(data=1, grad=0) Value(data=2, grad=0)
  Value(data=3, grad=0)]
 [Value(data=4, grad=0) Value(data=5, grad=0) Value(data=6, grad=0)
  Value(data=7, grad=0)]
 [Value(data=8, grad=0) Value(data=9, grad=0) Value(data=10, grad=0)
  Value(data=11, grad=0)]]

In [24]:
Tensor(np.maximum(ar_t.data, Value(5)))

Tensor
[[Value(data=5, grad=0) Value(data=5, grad=0) Value(data=5, grad=0)
  Value(data=5, grad=0)]
 [Value(data=5, grad=0) Value(data=5, grad=0) Value(data=6, grad=0)
  Value(data=7, grad=0)]
 [Value(data=8, grad=0) Value(data=9, grad=0) Value(data=10, grad=0)
  Value(data=11, grad=0)]]

### CrossEntropyLoss

In [26]:
y = [1, 3, 0]
[np.arange(len(y)), y]

[array([0, 1, 2]), [1, 3, 0]]

In [27]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
ar[np.arange(len(y)), y]

array([1, 7, 8])

In [29]:
[np.arange(len(y)), y]

[array([0, 1, 2]), [1, 3, 0]]

In [30]:
ar[[0, 1, 2], y]

array([1, 7, 8])

In [31]:
ar_t.data.sum(None)

Value(data=66, grad=0)

In [32]:
ar.mean(1)

array([1.5, 5.5, 9.5])

In [33]:
ar_t.data.sum()

Value(data=66, grad=0)

In [34]:
ar1 = np.arange(6).reshape(2, 3)
ar1

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
ar1_t = Tensor(ar1)
ar1_t

Tensor
[[Value(data=0, grad=0) Value(data=1, grad=0) Value(data=2, grad=0)]
 [Value(data=3, grad=0) Value(data=4, grad=0) Value(data=5, grad=0)]]

In [41]:
ar1_t.exp().mean()

Tensor
Value(data=39.03403066438303, grad=0)

In [39]:
ar1_t.exp().shape()

(2, 3)

In [40]:
np.exp(ar1).mean()

39.03403066438303